name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: get_version
        run: |
          echo "VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f2 | cut -d '+' -f1)" >> $GITHUB_OUTPUT

  build:
    needs: extract-version
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ needs.extract-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.os == 'windows-latest' && '~\AppData\Local\Pub\Cache' || (matrix.os == 'macos-latest' && '~/Library/Caches/CocoaPods' || '~/.pub-cache') }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/pubspec.lock') }}

      - name: Install build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: '3.32.0-0.3.pre'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Platform-specific build
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest)
              flutter build linux --release
              cd build/linux/x64/release/bundle
              tar -czvf HackerKit-v${VERSION}-linux-release.tar.gz *
              ;;
            windows-latest)
              flutter build windows --release
              cd build/windows/x64/runner/Release
              Compress-Archive -Path * -DestinationPath HackerKit-v${env:VERSION}-windows-release.zip
              ;;
            macos-latest)
              flutter build macos --release
              cd build/macos/Build/Products/Release
              zip -r HackerKit-v${VERSION}-macos-release.zip hackerkit_next.app
              ;;
          esac

      - name: Upload build artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/**/HackerKit-v${{ env.VERSION }}-*-release.*

  build-android:
    needs: extract-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.extract-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Android dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: '3.32.0-0.3.pre'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Decode and prepare keystore
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.jks
            cat <<EOF > android/key.properties
            storeFile=my-release-key.jks
            storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
            keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
            EOF
          fi

      - name: Build Split APKs
        run: flutter build apk --release --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      - name: Rename APKs with version
        run: |
          mkdir -p release-apks
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk release-apks/HackerKit-v${VERSION}-armeabi-v7a-release.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk release-apks/HackerKit-v${VERSION}-arm64-v8a-release.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk release-apks/HackerKit-v${VERSION}-x86_64-release.apk

      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-apks/HackerKit-v${{ env.VERSION }}-armeabi-v7a-release.apk
            release-apks/HackerKit-v${{ env.VERSION }}-arm64-v8a-release.apk
            release-apks/HackerKit-v${{ env.VERSION }}-x86_64-release.apk